export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const START_DOWNLOAD_USERS = 'START_DOWNLOAD_USERS';
export const DOWNLOAD_USERS_SUCCESS = 'DOWNLOAD_USERS_SUCCESS';
export const DOWNLOAD_USERS_ERROR = 'DOWNLOAD_USERS_ERROR';

export const GET_USER_DELETED = 'GET_USER_DELETED';
export const USER_DELETED_SUCCESS = 'USER_DELETED_SUCCESS';
export const USER_DELETED_ERROR = 'USER_DELETED_ERROR';

export const GET_USER_EDIT = 'GET_USER_EDIT';
export const START_EDITION_USER = 'START_EDITION_USER';
export const USER_EDITED_SUCCESS = 'USER_EDITED_SUCCESS';
export const USER_EDITED_ERROR = 'USER_EDITED_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';